### ISSUE TITLE
GSP Person Gender and Sex Segment

### ISSUE THREAD

**Issue by lpg-tech** [lpg-tech/HL7-V2#12]
p 37f.

fhir.ch says:

gender -> card. :  0..1  -> Datatype: code   -> valueSet:  male \| female \| other

[ http://fhir.ch/ig/ch-core/StructureDefinition-ch-core-patient.html ]

HL7 V2.8, TBL 0001:

VALUE | DESCRIPTION | COMMENT
-- | -- | --
A | Ambiguous |  
F | Female |  
M | Male |  
N | Not applicable |  
O | Other |  
U | Unknown

**Comment by bheggli** [comment]
Dieses Segment bezeichnet die sexuelle Orientierung des Patienten und diese Werte umfassen nicht nur M / F sondern auch Lesbian , gay queer. Eine Anpassung an der Beschreibung ist meiner Meinung nach daher nicht notwendig.

**Comment by lpg-tech** [comment]
Geschlecht als Identifikationsattribut wirt mit PID-8 abgedeckt
